import { Languages } from '../Languages';

export const postNoticeData = {
  [Languages.KO]: {
    TITLE: '구인 글 등록하기',
    COMPANY_NAME: '회사명',
    EMPLOYER_NAME: '담당자명',
    COMPANY_SCALE: '회사규모',
    AREA: '근무지 주소',
    SALARY: '급여',
    MAJOR_BUSINESS: '업무내용',
    WORKDURATION: '근무기간',
    WORKDAYS: '근무요일',
    WORKHOURS: '근무시간',
    WORKTYPE: '고용형태',
    REQUESTED_CAREER: '지원조건',
    ELIGIBILITY_CRITERIA: '비자조건',
    PREFERRED_CONDITIONS: '우대사항',
    SUBMIT: '등록하기',
  },
  [Languages.VE]: {
    TITLE: 'Đăng thông báo tuyển dụng',
    COMPANY_NAME: 'Tên công ty',
    EMPLOYER_NAME: 'Tên người phụ trách',
    COMPANY_SCALE: 'Quy mô công ty',
    AREA: 'Địa chỉ làm việc',
    SALARY: 'Lương',
    MAJOR_BUSINESS: 'Nội dung công việc',
    WORKDURATION: 'Thời gian làm việc',
    WORKDAYS: 'Ngày làm việc trong tuần',
    WORKHOURS: 'Giờ làm việc',
    WORKTYPE: 'Hình thức lao động',
    REQUESTED_CAREER: 'Yêu cầu kinh nghiệm',
    ELIGIBILITY_CRITERIA: 'Điều kiện về visa',
    PREFERRED_CONDITIONS: 'Ưu tiên',
    SUBMIT: 'Đăng ký',
  },
};
