import { Languages } from '../Languages';

export const postNoticeData = {
  [Languages.KO]: {
    TITLE: '구인 글 등록하기',
    NOTICE_TITLE: '제목',
    COMPANY_NAME: '회사명',
    EMPLOYER_NAME: '담당자명',
    COMPANY_SCALE: '회사규모',
    AREA: '근무지 주소',
    SALARY: '급여',
    MAJOR_BUSINESS: '업무내용',
    WORKDURATION: '근무기간',
    WORKDAYS: '근무요일',
    WORKHOURS: '근무시간',
    WORKTYPE: '고용형태',
    REQUESTED_CAREER: '지원조건',
    ELIGIBILITY_CRITERIA: '비자조건',
    PREFERRED_CONDITIONS: '우대사항',
    ERROR: {
      NOTICE_TITLE: '구인글 제목을 입력해주세요.',
      COMPANY_NAME: '회사명을 입력해주세요.',
      EMPLOYER_NAME: '고용주 이름을 입력해주세요.',
      COMPANY_SCALE: '회사 규모를 입력해주세요.',
      AREA: '지역을 입력해주세요.',
      SALARY: '급여를 입력해주세요.',
      MAJOR_BUSINESS: '주요 업무 내용을 입력해주세요.',
      WORKDURATION: '근무 기간을 입력해주세요.',
      WORKDAYS: '근무 요일을 입력해주세요.',
      WORKHOURS: '근무 시간을 입력해주세요.',
      WORKTYPE: '고용 형태를 입력해주세요.',
      REQUESTED_CAREER: '지원조건을 입력해주세요.',
      ELIGIBILITY_CRITERIA: '비자 자격 요건을 입력해주세요.',
      PREFERRED_CONDITIONS: '우대사항을 입력해주세요.',
    },
    SUBMIT_CHECK: '구인글을 등록하시겠습니까?',
    SUBMIT: '등록하기',
  },
  [Languages.VE]: {
    TITLE: 'Đăng thông báo tuyển dụng',
    NOTICE_TITLE: 'Tiêu đề',
    COMPANY_NAME: 'Tên công ty',
    EMPLOYER_NAME: 'Tên người phụ trách',
    COMPANY_SCALE: 'Quy mô công ty',
    AREA: 'Địa chỉ làm việc',
    SALARY: 'Lương',
    MAJOR_BUSINESS: 'Nội dung công việc',
    WORKDURATION: 'Thời gian làm việc',
    WORKDAYS: 'Ngày làm việc trong tuần',
    WORKHOURS: 'Giờ làm việc',
    WORKTYPE: 'Hình thức lao động',
    REQUESTED_CAREER: 'Yêu cầu kinh nghiệm',
    ELIGIBILITY_CRITERIA: 'Điều kiện về visa',
    PREFERRED_CONDITIONS: 'Ưu tiên',
    ERROR: {
      NOTICE_TITLE: 'Vui lòng nhập tiêu đề bài đăng tuyển dụng.',
      COMPANY_NAME: 'Vui lòng nhập tên công ty.',
      EMPLOYER_NAME: 'Vui lòng nhập tên nhà tuyển dụng.',
      COMPANY_SCALE: 'Vui lòng nhập quy mô công ty.',
      AREA: 'Vui lòng nhập khu vực.',
      SALARY: 'Vui lòng nhập mức lương.',
      MAJOR_BUSINESS: 'Vui lòng nhập nội dung công việc chính.',
      WORKDURATION: 'Vui lòng nhập thời gian làm việc.',
      WORKDAYS: 'Vui lòng nhập ngày làm việc.',
      WORKHOURS: 'Vui lòng nhập giờ làm việc.',
      WORKTYPE: 'Vui lòng nhập hình thức làm việc.',
      REQUESTED_CAREER: 'Vui lòng nhập điều kiện ứng tuyển.',
      ELIGIBILITY_CRITERIA: 'Vui lòng nhập yêu cầu về điều kiện visa.',
      PREFERRED_CONDITIONS: 'Vui lòng nhập điều kiện ưu tiên.',
    },
    SUBMIT_CHECK: 'Bạn có muốn đăng bài tuyển dụng không?',
    SUBMIT: 'Đăng ký',
  },
};
